In [2]:
import os
import numpy as np

In [3]:
dp = "/home/wsx/pointcloud_research/data/nuscenes/samples/LIDAR_TOP/"
f = os.listdir(dp)

In [5]:
fp = os.path.join(dp, f[0])
arr = np.fromfile(fp, dtype=np.float32)

In [7]:
arr.shape

(173760,)

In [9]:
b = arr.reshape(-1, 5)

In [10]:
b.shape

(34752, 5)

In [11]:
b

array([[-3.11151433e+00, -4.25875634e-01, -1.86787534e+00,
         1.00000000e+00,  0.00000000e+00],
       [-3.31420445e+00, -4.23742235e-01, -1.88473475e+00,
         1.00000000e+00,  1.00000000e+00],
       [-3.45363188e+00, -4.22432363e-01, -1.85894501e+00,
         1.00000000e+00,  2.00000000e+00],
       ...,
       [ 7.56133829e-07,  3.17226877e-05,  1.55102555e-06,
         5.00000000e+00,  2.90000000e+01],
       [ 7.56133829e-07,  3.17226877e-05,  1.55102555e-06,
         1.39000000e+02,  3.00000000e+01],
       [-1.06917925e+01,  4.29347605e-02,  2.01445580e+00,
         2.20000000e+01,  3.10000000e+01]], dtype=float32)

In [12]:
f[0]

'n008-2018-09-18-14-35-12-0400__LIDAR_TOP__1537296188900729.pcd.bin'

In [13]:
b[:, -1]

array([ 0.,  1.,  2., ..., 29., 30., 31.], dtype=float32)

In [20]:
for i in b[:, -2]:
    print(i)

1.0
1.0
1.0
0.0
1.0
5.0
2.0
1.0
39.0
42.0
1.0
3.0
1.0
1.0
3.0
1.0
1.0
2.0
3.0
3.0
28.0
0.0
44.0
1.0
10.0
18.0
81.0
5.0
29.0
56.0
36.0
15.0
1.0
1.0
1.0
0.0
1.0
4.0
2.0
1.0
81.0
7.0
1.0
2.0
2.0
1.0
4.0
7.0
1.0
52.0
2.0
5.0
31.0
0.0
15.0
4.0
1.0
9.0
81.0
56.0
30.0
21.0
85.0
35.0
1.0
1.0
1.0
0.0
1.0
6.0
3.0
1.0
100.0
7.0
1.0
3.0
2.0
1.0
4.0
66.0
7.0
9.0
4.0
11.0
19.0
2.0
5.0
1.0
1.0
9.0
78.0
25.0
29.0
21.0
90.0
22.0
1.0
1.0
1.0
0.0
1.0
8.0
2.0
1.0
100.0
13.0
1.0
2.0
3.0
1.0
4.0
10.0
7.0
100.0
56.0
101.0
56.0
100.0
0.0
2.0
1.0
9.0
78.0
26.0
33.0
8.0
10.0
7.0
1.0
1.0
1.0
0.0
1.0
10.0
2.0
1.0
101.0
94.0
1.0
3.0
4.0
1.0
4.0
13.0
8.0
10.0
3.0
162.0
23.0
72.0
92.0
9.0
2.0
9.0
56.0
21.0
30.0
4.0
18.0
5.0
1.0
1.0
1.0
0.0
1.0
13.0
2.0
1.0
100.0
100.0
1.0
3.0
4.0
1.0
4.0
7.0
1.0
1.0
2.0
103.0
67.0
12.0
2.0
4.0
2.0
1.0
18.0
35.0
29.0
47.0
78.0
6.0
0.0
1.0
1.0
0.0
1.0
12.0
2.0
1.0
105.0
22.0
1.0
2.0
4.0
1.0
4.0
3.0
2.0
1.0
3.0
28.0
83.0
0.0
0.0
3.0
1.0
1.0
9.0
28.0
30.0
43.0
99.0
56.0
0.0
1.0
1.0
0.0


In [18]:
np.unique(b[:, -2])

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 105., 106., 107., 108., 109., 110., 111.,
       112., 113., 114., 115., 117., 118., 120., 121., 122., 123., 124.,
       125., 126., 127., 128., 129., 130., 131., 132., 133., 135., 136.,
       137., 138., 139., 140., 141., 142., 143., 144., 145., 146., 147.,
       149., 150., 151., 152., 153., 155., 156., 15